// SPDX-FileCopyrightText: 2022 Guy Boldon, Eren Simsek and contributors
// SPDX-License-Identifier: GPL-3.0-or-later

pub mod aquacomputer;
pub mod asus_ryujin;
pub mod aura_led;
pub mod commander_core;
pub mod commander_pro;
pub mod control_hub;
pub mod coolit;
pub mod corsair_hid_psu;
pub mod device_support;
pub mod ga2_lcd;
pub mod h1v2;
pub mod hydro_690_lc;
pub mod hydro_platinum;
pub mod hydro_pro;
pub mod kraken2;
pub mod kraken_x3;
pub mod kraken_z3;
pub mod kraken_z3_mock;
pub mod legacy_690_lc;
pub mod lianli_uni;
pub mod modern_690_lc;
pub mod mpg_cooler;
pub mod msi_acpi_ec;
pub mod nzxt_epsu;
pub mod rgb_fusion2;
pub mod smart_device;
pub mod smart_device2;
