#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Guy Boldon and contributors
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the desktop notification icons.

Drawn at the app icon's stroke weight (25 on a 256 canvas) with round caps and
joins, so they read as one family with it. Each icon keeps the framing it has
always had: round joins mean the heavier stroke still clears the canvas, and the
ink only grows half a stroke per side.

The bars are filled rects, not strokes. As a stroked vertical path the geometry
bbox is zero-width, and `#grad` is objectBoundingBox, so it degenerates to a
flat colour there and the bar loses its gradient.

Usage:  scripts/gen-notification-icons.py
"""
import argparse
import io
import pathlib

__VERSION__ = "1"

try:
    import cairosvg
except ImportError:
    raise SystemExit("Missing dependency: pip install cairosvg") from None
try:
    from PIL import Image
except ImportError:
    raise SystemExit("Missing dependency: pip install pillow") from None

ROOT = pathlib.Path(__file__).resolve().parent.parent
TARGETS = (ROOT / "packaging/metadata", ROOT / "coolercontrol-ui/public/icons")
SIZE = 512
STROKE = 25
HALF = STROKE / 2

HEAD = """<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--
  SPDX-FileCopyrightText: 2026 Guy Boldon and contributors
  SPDX-License-Identifier: GPL-3.0-or-later

  Generated by scripts/gen-notification-icons.py.
-->
<svg width="256" height="256" viewBox="0 0 256 256" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="grad" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" stop-color="#3b82f6"/>
      <stop offset="50%" stop-color="#8b5cf6"/>
      <stop offset="100%" stop-color="#ec4899"/>
    </linearGradient>
  </defs>
"""

ENDS = 'stroke-linecap="round" stroke-linejoin="round"'
STROKED = f'fill="none" stroke="url(#grad)" stroke-width="{STROKE}" {ENDS}'


def bar(cx, y, height):
    """A filled rect, rounded to look like a round-capped stroke."""
    return (
        f'  <rect x="{cx - HALF:g}" y="{y:g}" width="{STROKE}" height="{height:g}"'
        f' rx="{HALF:g}" fill="url(#grad)" />'
    )


def dot(cx, cy):
    return f'  <circle cx="{cx:g}" cy="{cy:g}" r="{HALF:g}" fill="url(#grad)" />'


ICONS = {
    # Power symbol: a ring with the stem crossing its top.
    "shutdown": [f'  <circle cx="128" cy="144" r="80" {STROKED} />', bar(128, 32, 80)],
    "information": [bar(128, 112, 80), dot(128, 72)],
    "alert-triggered": [
        f'  <polygon points="128,32 240,224 16,224" {STROKED} />',
        bar(128, 96, 64),
        dot(128, 192),
    ],
    "alert-resolved": [f'  <path d="M 64,128 L 112,176 L 192,80" {STROKED} />'],
    # Lines as paths: some renderers ignore the <line> element outright.
    "alert-error": [
        f'  <polygon points="128,32 240,224 16,224" {STROKED} />',
        f'  <path d="M 92,132 L 164,204" {STROKED} />',
        f'  <path d="M 164,132 L 92,204" {STROKED} />',
    ],
}


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("-v", "--version", action="version", version=f"\n {__VERSION__}")
    ap.parse_args()

    for name, parts in ICONS.items():
        svg = HEAD + "\n".join(parts) + "\n</svg>\n"
        png = cairosvg.svg2png(
            bytestring=svg.encode(), output_width=SIZE, output_height=SIZE
        )
        img = Image.open(io.BytesIO(png)).convert("RGBA")
        for target in TARGETS:
            img.save(target / f"{name}.png")
        print(f"wrote {name}.png")


if __name__ == "__main__":
    main()
